### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by neonila-kunyk** [neonila-kunyk/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by neonilakunyk** [comment]
— I am a Professor Emeritus in Carnegie Mellon’s School of Computer Science (SCS). That means I am formally retired, but still active in research, advising, and departmental activities. At first, it worried me that I was better known as a smiley creator than an AI researcher. But then I decided that it’s even fun to be a little famous for something, even if it’s not a business that I’ve devoted my whole life to.
