### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by neonila-kunyk** [neonila-kunyk/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by neonilakunyk** [comment]
**Scott E. Fahlman**
Phone: +1-412-268-2575
E-mail: sef@cs.cmu.edu
Facebook: https://www.facebook.com/scott.fahlman
Quora: https://www.quora.com/profile/Scott-E-Fahlman
